Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MisVacaciones.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using MisVacaciones.Services;
using System.Net.Mail;
using System.Text.RegularExpressions;

namespace MisVacaciones.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IComputerVisionService _computerVisionService;
        private readonly ILocationService _locationService;
        private readonly IWeatherService _weatherService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public IndexModel(ILogger<IndexModel> logger, IWebHostEnvironment hostEnvironment)
        {
            _logger = logger;
            _computerVisionService = new ComputerVisionService();
            _locationService = new LocationService();
            _weatherService = new WeatherService();
            this._hostEnvironment = hostEnvironment;
        }

        [BindProperty]
        public FileUpload fileUpload { get; set; }
        public void OnGet()
        {
            ViewData["SuccessMessage"] = "";
        }
        public async Task<IActionResult> OnPostUpload(FileUpload fileUpload)
        {
            string fullPath = _hostEnvironment.WebRootPath + "/UploadImages/";
            if (!Directory.Exists(fullPath))
            {
                Directory.CreateDirectory(fullPath);
            }
            var formFile = fileUpload.FormFile;
            if (formFile.Length > 0)
            {
                var filePath = Path.Combine(fullPath, formFile.FileName);
                ViewData["ImageUrl"] = formFile.FileName;
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await formFile.CopyToAsync(stream);
                }

                // using service to analyze the image  
                var imageAnalysis = await _computerVisionService.AnalyzeImageUrl(filePath);
                if (imageAnalysis.imageAnalysisResult != null)
                {
                    ViewData["ImageAnalysisViewModel"] = imageAnalysis;
                    
                    // using service to get location 
                    if (imageAnalysis.imageAnalysisResult.Categories.Count >= 1 &&
                        imageAnalysis.imageAnalysisResult.Categories[0].Detail != null &&
                        imageAnalysis.imageAnalysisResult.Categories[0].Detail.Landmarks.Count >= 1)
                    {
                        var location = imageAnalysis.imageAnalysisResult.Categories[0].Detail.Landmarks[0].Name;
                        if (location != null)
                        {
                            var coordinates = await _locationService.AnalyzeAddress(location);
                            if (coordinates != null) 
                            {
                                ViewData["Coordinates"] = coordinates;

                                //using service to get weather
                                var weather = await _weatherService.GetWeather(coordinates.longitude, coordinates.latitude);

                                if (weather != null) 
                                {
                                    ViewData["Weather"] = weather;
                                }
                            }
                        }
                    }
                }
            }

            ViewData["SuccessMessage"] = fileUpload.FormFile.FileName.ToString() + " file uploaded!!";


            return Page();
        }
        public void OnPostEnviar(string correo, string cuerpo, string hostname)
        {
            cuerpo = replaceSRC(cuerpo, hostname);
            string EmailOrigen = "bruteforce.misvacaciones@gmail.com";
            string EmailDestion = correo;
            string contraseña = "123genesis";
            string Cuerpo = cuerpo;
            MailMessage mailMessage = new MailMessage(EmailOrigen, EmailDestion, "Mis vacaciones: información de ubicación", Cuerpo);
            mailMessage.IsBodyHtml = true;
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com");
            smtpClient.EnableSsl = true;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Port = 587;
            smtpClient.Credentials = new System.Net.NetworkCredential(EmailOrigen, contraseña);
            smtpClient.Send(mailMessage);
            smtpClient.Dispose();
        }

        private string replaceSRC(string html, string host) 
        {
            html = html.Replace("UploadImages", host + "/UploadImages");
            html = html.Replace("assets", host + "/assets");


            html = html.Replace("\n", " ");
            html = html.Replace("\t", " ");
            html = Regex.Replace(html, "\\s+", " ");
            html = Regex.Replace(html, "<head.*?</head>", "", RegexOptions.IgnoreCase | RegexOptions.Singleline);
            html = Regex.Replace(html, "<script.*?</script>", "", RegexOptions.IgnoreCase | RegexOptions.Singleline);
            html = Regex.Replace(html, "<form.*?</form>", "", RegexOptions.IgnoreCase | RegexOptions.Singleline);
            html = Regex.Replace(html, "<header.*?</header>", "", RegexOptions.IgnoreCase | RegexOptions.Singleline);
            
            return html;
        }

        public class FileUpload
        {
            [Required]
            [Display(Name = "File")]
            public IFormFile FormFile { get; set; }
            public string SuccessMessage { get; set; }
        }


    }
}

Pages/Photo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using MisVacaciones.Services;

namespace MisVacaciones.Pages
{
    public class PhotoModel : PageModel
    {
        private readonly ILogger<PhotoModel> _logger;
        private readonly IComputerVisionService _computerVisionService;
        private readonly ILocationService _locationService;
        private readonly IWeatherService _weatherService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public PhotoModel(ILogger<PhotoModel> logger, IWebHostEnvironment hostEnvironment)
        {
            _logger = logger;
            _computerVisionService = new ComputerVisionService();
            _locationService = new LocationService();
            _weatherService = new WeatherService();
            this._hostEnvironment = hostEnvironment;
        }

        [BindProperty]
        public FileUpload fileUpload { get; set; }
        public void OnGet()
        {
            ViewData["SuccessMessage"] = "";
        }
        public async Task<IActionResult> OnPostUploadPhoto(FileUpload fileUpload)
        {
            string fullPath = _hostEnvironment.WebRootPath + "/UploadImages/";
            if (!Directory.Exists(fullPath))
            {
                Directory.CreateDirectory(fullPath);
            }
            var formFile = fileUpload.FormFile;
            if (formFile.Length > 0)
            {
                var filePath = Path.Combine(fullPath, formFile.FileName);
                ViewData["ImageUrl"] = formFile.FileName;
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await formFile.CopyToAsync(stream);
                }

                // using service to analyze the image  
                var imageAnalysis = await _computerVisionService.AnalyzeImageUrl(filePath);
                if (imageAnalysis.imageAnalysisResult != null)
                {
                    ViewData["ImageAnalysisViewModel"] = imageAnalysis;
                    
                    // using service to get location 
                    if (imageAnalysis.imageAnalysisResult.Categories.Count >= 1 &&
                        imageAnalysis.imageAnalysisResult.Categories[0].Detail != null &&
                        imageAnalysis.imageAnalysisResult.Categories[0].Detail.Landmarks.Count >= 1)
                    {
                        var location = imageAnalysis.imageAnalysisResult.Categories[0].Detail.Landmarks[0].Name;
                        if (location != null)
                        {
                            var coordinates = await _locationService.AnalyzeAddress(location);
                            if (coordinates != null) 
                            {
                                ViewData["Coordinates"] = coordinates;

                                //using service to get weather
                                var weather = await _weatherService.GetWeather(coordinates.longitude, coordinates.latitude);

                                if (weather != null) 
                                {
                                    ViewData["Weather"] = weather;
                                }
                            }
                        }
                    }
                }
            }

            ViewData["SuccessMessage"] = fileUpload.FormFile.FileName.ToString() + " file uploaded!!";


            return Page();
        }
        public class FileUpload
        {
            [Required]
            [Display(Name = "File")]
            public IFormFile FormFile { get; set; }
            public string SuccessMessage { get; set; }
        }


    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MisVacaciones.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page

@model IndexModel
@using MisVacaciones.Services.Dto;
@using QuickType;
@{
    ViewData["Title"] = "Index";
}

<div class="loading" align="center" onload="setTimeout() onclick="setTimeout()">
        Loading. Please wait.<br/>
        <br/>
        <img src="https://cdn.dribbble.com/users/722246/screenshots/4400319/loading_crescor_dribbble.gif" alt=""/>
</div>

<script type="text/javascript">
    setTimeout(function () {
        document.body.removeChild(modal);
        loading.style.display = "none";
    }, 2000); //Delay just used for example and must be set to 0.
</script>

<script type="text/javascript">
        var modal, loading;
        function ShowProgress() {
            modal = document.createElement("DIV");
            modal.className = "modal";
            document.body.appendChild(modal);
            loading = document.getElementsByClassName("loading")[0];
            loading.style.display = "block";
            var top = Math.max(window.innerHeight / 2 - loading.offsetHeight / 2, 0);
            var left = Math.max(window.innerWidth / 2 - loading.offsetWidth / 2, 0);
            loading.style.top = top + "px";
            loading.style.left = left + "px";
        };
        ShowProgress();
    </script>

<div class="text-center">
    <h2>My Vacations</h2>
    <br>
</div>

<form enctype="multipart/form-data" method="post">
    @*File Upload part*@
    <div class="form-group">
        <label class="file">
            <input type="file" asp-for="fileUpload.FormFile" multiple aria-label="File browser example">
            <span class="file-custom"></span>
        </label>
        <input asp-page-handler="Upload" class="btn btn-primary" type="submit" value="Upload">
    </div>
</form>
    @{
        if (ViewData["SuccessMessage"] != null)
        {
            <span class="badge badge-success"> @ViewData["SuccessMessage"]</span>
        }
    }

    @*Displaying Analysis results*@
    <div class="row">
        <div class="col-sm">

            @if (ViewData["ImageUrl"] != null)
            {
                //Image
                var imageUrl = Convert.ToString(ViewData["ImageUrl"]);
                <img src="UploadImages/@imageUrl" class="img-thumbnail" />

                //Vote
                <!-- LikeBtn.com BEGIN -->
                <br>
                <span class="likebtn-wrapper" data-theme="large" data-ef_voting="push" data-voting_frequency="10" data-counter_frmt="km" data-popup_width="50" data-share_size="small" data-loader_show="true"></span>
                <script>(function (d, e, s) { if (d.getElementById("likebtn_wjs")) return; a = d.createElement(e); m = d.getElementsByTagName(e)[0]; a.async = 1; a.id = "likebtn_wjs"; a.src = s; m.parentNode.insertBefore(a, m) })(document, "script", "//w.likebtn.com/js/w/widget.js");</script>
                <!-- LikeBtn.com END -->


                <!-- Email -->
                <script>
                    function obtenerHtml() {
                        var input = document.getElementById("cualquiernombre");
                        input.value = document.documentElement.innerHTML;

                        var inputHOST = document.getElementById("hostname");
                        inputHOST.value = window.location.hostname;
                    }
                </script>
                <form enctype="multipart/form-data" method="post">
                    <div class="form-group">
                        <label for="correo">
                            <span>Correo: </span>
                            <input type="text" name="correo" onclick="obtenerHtml()" />
                            <input type="hidden" name="cuerpo" id="cualquiernombre" />
                            <input type="hidden" name="hostname" id="hostname" />
                            <input asp-page-handler="Enviar" class="btn btn-primary" type="submit" value="Enviar">
                        </label>
                        <br>
                    </div>
                </form>
                <!-- /Email -->
            }
        </div>
        <div class="col-sm">
            <p>
                @if (ViewData["ImageAnalysisViewModel"] != null)
                {
                    var imageAnalysisView = (ImageAnalysisViewModel)ViewData["ImageAnalysisViewModel"];
                    <h5>Description</h5>
                    foreach (var caption in imageAnalysisView.imageAnalysisResult.Description.Captions)
                    {
                        <span class="text-info"> @caption.Text: with confidence @caption.Confidence</span><br />
                    }
                    foreach (var category in imageAnalysisView.imageAnalysisResult.Categories)
                    {
                        if (category.Detail?.Landmarks != null)
                        {
                            <h5>Landmark</h5>
                            foreach (var landmark in category.Detail.Landmarks)
                            {
                                <span class="text-success"> @landmark.Name with confidence: @landmark.Confidence</span><br />
                                break;
                            }
                            break;
                        }
                    }
                    @if (ViewData["Coordinates"] != null)
                    {
                        var coordinatesModel = (CoordinatesViewModel)ViewData["Coordinates"];
                        <h5>Coordinates</h5>
                        <span class="badge badge-warning">Latitude: @coordinatesModel.latitude </span>
                        <span class="badge badge-warning">Longitude: @coordinatesModel.longitude </span>

                        <h5>Location</h5>
                        <iframe width="500"
                                height="400"
                                style="border:0"
                                loading="lazy"
                                allowfullscreen
                                src="https://www.google.com/maps/embed/v1/place?key=AIzaSyABjlTQ4n7GEdS3gErCOgGiirYFAelOMeA&q=@coordinatesModel.latitude,@coordinatesModel.longitude">
                        </iframe>
                    }
                    @if (ViewData["Weather"] != null)
                    {
                        <h5>Recommendation</h5>
                        <ul class="list-group">

                            @{var weatherModel = (Weather)ViewData["Weather"];
                                var temp = weatherModel.List[0].Temp.Day;}

                            @if (temp <= 17)
                            {
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="image-parent">
                                        <img src="assets/invierno_h.png" class="img-fluid">
                                    </div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="image-parent">
                                        <img src="assets/invierno_m.png" class="img-fluid">
                                    </div>
                                </li>
                            }
                            else if (temp > 17 && temp <= 22)
                            {
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="image-parent">
                                        <img src="assets/fresco_h.png" class="img-fluid">
                                    </div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="image-parent">
                                        <img src="assets/fresco_m.png" class="img-fluid">
                                    </div>
                                </li>
                            }
                            else if (temp > 22)
                            {
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="image-parent">
                                        <img src="assets/verano_h.png" class="img-fluid">
                                    </div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="image-parent">
                                        <img src="assets/verano_m.png" class="img-fluid">
                                    </div>
                                </li>
                            }
                        </ul>
                    }
                    <h5>Tags</h5>
                    @foreach (var tag in imageAnalysisView.imageAnalysisResult.Tags)
                    {
                        <span class="badge badge-success">@tag.Name - @tag.Confidence</span>
                    }
                }
            </p>
        </div>
        <div class="col-sm">
            @if (ViewData["Weather"] != null)
            {
                <h5>Weather</h5>
                <ul class="list-group">
                    @{var weatherModel = (Weather)ViewData["Weather"];}
                    @foreach (var item in weatherModel.List)
                    {
                        var timestamp = item.Dt;
                        string weatherlink = $"https://openweathermap.org/img/wn/{item.Weather[0].Icon}.png";
                        // Unix timestamp is seconds past epoch
                        DateTime dateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
                        dateTime = dateTime.AddSeconds(timestamp).ToLocalTime();


                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @dateTime.Date.ToShortDateString() <br>
                            @item.Weather[0].Description <br>
                            @item.Temp.Day °C
                            <div class="image-parent">
                                <img src=" @weatherlink " class="img-fluid">
                            </div>
                        </li>
                    }
                </ul>
            }
        </div>
    </div>